services:
  - type: worker
    name: homework-bot
    runtime: python
    buildCommand: pip install -r bot/requirements.txt
    startCommand: python bot/bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN_2
        sync: false
      - key: TEACHER_GROUP_ID_2
        value: "-5516510250"

